config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'pages/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: {maximum: 25}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private

    def sign_up_params
        params.require(:user).permit(:name,:username,:email,:password,:password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:name,:username,:email,:password,:password_confirmation,:current_password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Code4pro</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <%= render partial: 'shared/header' %>
    <%= render partial: 'shared/message' %>      

    <main class="indigo lighten-4"> 
        <div class="container">
          <%= yield %>
        </div>
    
    </main>
   
    <%= render partial: 'shared/footer' %> 
       
    <script src="https://kit.fontawesome.com/444a4d875c.js" crossorigin="anonymous"></script>
    <script> $(document).ready(function(){
        $('.sidenav').sidenav();
        $(".dropdown-trigger").dropdown();
        document.getElementById("current-year").innerHTML = new Date().getFullYear();
      });
    </script>        
  </body>
</html>

app/views/pages/about.html.erb
<h3>About Me</h3>

<div class="card z-depth-3">
	<div class="card-content white-text">
    <div class="row">
      <div class="col m6">
			<a class="twitter-timeline" href="https://twitter.com/MurangwaMorris" data-widget-id="587633580509044736">Tweets by @Code4Startup</a>
			<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
		</div>
		<div class="col m6">
			<div class="card-panel grey lighten-5 z-depth-1">
				<div class="row valign-wrapper">
					<div class="col s3">
						<%= image_tag "avatar.JPG", class: "circle responsive-img" %>
					</div>
					<div class="col s9">
						<span class="black-text">
							I don't know what to say. Let the world tell you more... :)
						</span>
					</div>
				</div>
			</div>
		</div>
    </div>
	</div>
</div>

app/views/shared/_footer.html.erb
 <footer class="page-footer  teal darken-4">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Code4Pro</h5>
                <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Follow Us</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" href="#!"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                  <li><a class="grey-text text-lighten-3" href="#!"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                  <li><a class="grey-text text-lighten-3" href="#!"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
                  <li><a class="grey-text text-lighten-3" href="#!"><i class="fa fa-github" aria-hidden="true"></i></a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
           <p>Copyright &copy; <span id="current-year"></span> Code4Pro</p>
            <%= link_to 'About Us', pages_about_path, class: "grey-text text-lighten-4 right" %>
            </div>
          </div>
 </footer>

app/views/shared/_header.html.erb
<header>
     <ul id="dropdown1" class="dropdown-content">
      <li><a href="#!">My Profile</a></li>
      <li><a href="#!">My Courses</a></li>
      <li class="divider"></li>
      <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
    </ul>

     <ul id="dropdown2" class="dropdown-content">
      <li><a href="#!">My Profile</a></li>
      <li><a href="#!">My Courses</a></li>
      <li class="divider"></li>
      <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
    </ul>
    
    <nav class=" teal darken-4 z-depth-2">
      <div class="container">
        <div class="nav-wrapper">
          <a href="#!" class="brand-logo">Code4Pro</a>
          <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
          <ul class="right hide-on-med-and-down">
            <li><a href="#">Courses</a></li>
            <% if !user_signed_in? %>
              <li><%= link_to 'Sign Up', new_user_registration_path %></li>
              <li><%= link_to 'Sign In', new_user_session_path %></li>
            <% else %>
              <li><a class="dropdown-trigger" href="#!" data-target="dropdown1"><%= current_user.email %><i class="material-icons right">arrow_drop_down</i></a></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
     <ul class="sidenav" id="mobile-demo">
      <li><a href="#">Courses</a></li>
     <% if !user_signed_in? %>
         <li><%= link_to 'Sign Up', new_user_registration_path %></li>
         <li><%= link_to 'Sign In', new_user_session_path %></li>
      <% else %>
         <li><a class="dropdown-trigger" href="#!" data-target="dropdown1"><%= current_user.email %><i class="material-icons right">arrow_drop_down</i></a></li>
    <% end %>
    </ul>
  </header>

app/views/shared/_message.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>